version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - "8000:3000"
    environment:
      TOKEN_KEY: "${TOKEN_KEY}"
  users:
    build: ./users-api
    ports:
      - "8080:3000"
    environment:
      MONGODB_CONNECTION_URI: "${MONGODB_CONNECTION_URI}"
      AUTH_API_ADDRESSS: "${AUTH_API_ADDRESSS}"
