apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: yeminko/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.97.190.230"
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: "tasks"
